version: '3.8'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - "./backend/.env"
  frontend:
    container_name: frontend
    build: ./events-app
    ports:
      - "3000:80"
    env_file:
      - "./events-app/.env"
    depends_on:
      - backend
  
    
